[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.13"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/willf/bloom"
  version = "2.0.3"
